### ISSUE TITLE
How to provide stand-alone functionality

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterSamples/Barcodes2#1]
One cool feature of Starcounter/Polyjuice is that we can run apps standalone or in a launcher. However, for small apps, the boilerplate of a standalone master page can be much bigger than the gist of the app itself. So how do we provide this feature?

## Design considerations

1. We don't want hidden magic. You should be able to see what the application does.
2. We don't want to bloat the code base of the app such that it obfuscates the core gist of it

## Suggestions

1. We could provide a minimal index.html master page with minimal ceremony while still avoiding magic,
2. **or** we could put the stand alone stuff as a part of the ```/tests``` to indicate that it is just a way to run your stuff in isolation,
3.  **or** we could have some reusable stand-alone stuff in the Polyjuice package,
4.  **or** we could do a combination of the above

**Comment by miyconst** [comment]
I vote for 1 & 3.

**Comment by dan31** [comment]
I believe that a better way to run app standalone would be to have a short set of files globally available for the app in the platform, so p.3 rather than p.2. The test then should include running app standalone as well, and it will be reusing those files.

**Comment by warpech** [comment]
My vote also goes for 3. At least in the beginning this should be opt-in:

We could provide `StandalonePage` class that extends `Page` with the following changes:
- the `Title` property sets the `<title>` value in HTML head (with the **app name** as the default value)
- if in standalone mode, the `Html` value leaves the server wrapped in HTML code required to support PuppetJs

In my app's master handler (the one that creates the view-model tree for the app state) would then be used like:

```c#
var master = new StandalonePage() {
 Html = "/Barcodes/BarcodesList.html"
}
```

**Comment by warpech** [comment]
The above idea is now implemented in: https://github.com/StarcounterSamples/Partial

With the following changes:

- the class is called `Partial` (not `StandalonePage`)
- the title property is called `ImplicitStandaloneTitle` (not `Title`)
- the HTML is not loaded from a static file but included in `Partial` class definition (as a string)

It is used in 3 projects now and so far there were no complaints. Which means that it works OK or was not properly tested :)

@miyconst, @chrhol could you give it a look? 

If all looks good then it would be nice to include it in Starcounter soon, because the benefits are great.

**Comment by warpech** [comment]
Implicit mode pushed to Starcounter. Follow up discussion there: https://github.com/Starcounter/Starcounter/issues/3176
